# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs
saccfiles: ['/tigress/anicola/DATA/HSC-LSS/HSC_processed/data/WIDE_GAMA15H_sirius_out/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/power_spectra_wdpj.sacc', '/tigress/anicola/DATA/HSC-LSS/HSC_processed/data/WIDE_GAMA09H_sirius_out/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/power_spectra_wdpj.sacc', '/tigress/anicola/DATA/HSC-LSS/HSC_processed/data/WIDE_WIDE12H_sirius_out/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/power_spectra_wdpj.sacc', '/tigress/anicola/DATA/HSC-LSS/HSC_processed/data/WIDE_VVDS_sirius_out/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/power_spectra_wdpj.sacc', '/tigress/anicola/DATA/HSC-LSS/HSC_processed/data/WIDE_XMMLSS_sirius_out/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/power_spectra_wdpj.sacc']


cl_params:
    fitHOD: 1
    modHOD: zevol
    fitNoise: 0
    corrHM: 1
    pzMethod: nz_demp
    bg:
        b_bin0: 1.
        b_bin1: 1.
        b_bin2: 1.
        b_bin3: 1.

sacc_params:
    cullCross: 0
    joinSaccs: 1
    singleBin: 0
    lmin: kmax
    lmax: kmax
    kmax: 1.

# Parameters to be fitted in MCMC
# [mapping_index, mean, min, max, std]
fit_params:
    zshift_bin0: [0, 0.0, -0.2, 0.2, 0.01]
    zshift_bin1: [1, 0.0, -0.2, 0.2, 0.01]
    zshift_bin2: [2, 0.0, -0.2, 0.2, 0.01]
    zshift_bin3: [3, 0.0, -0.2, 0.2, 0.01]
    lmmin_0: [4, 4., -5., 10., 0.5]
    lmmin_1: [5, 10., 0., 15., 0.5]
    m0_0: [6, -2., -5., 10., 0.5]
    m0_1: [7, 13., 0., 15., 0.5]
    m1_0: [8, 7., -5., 10., 0.5]
    m1_1: [9, 10., 0., 15., 0.5]

default_params:
    has_rsd: False
    has_magnification: null
    Omega_b: 0.0493
    Omega_k: 0.0
    sigma8: 0.8111
    h: 0.6736
    n_s: 0.9649
    Omega_c: 0.264
    transfer_function: boltzmann_class
    matter_power_spectrum: halofit
    sigm_0: 0.4
    sigm_1: 0.
    alpha_0: 1.0
    alpha_1: 0.
    fc_0: 1.
    fc_1: 0.

# Configuration parameters for cosmohammer
ch_config_params:
    path2output: /tigress/anicola/DATA/HSC-LSS/HSC_processed/analysis/covana_noiana_msksirius_cltheory_wssc_msksyst0_dpj0_dpb_bands1/chains
    chainsPrefix: mcm-chains_mPk=HOD_fix=alpha-fc-sigmaM_HOD=zevol_fit=pz-shifts+prior=0p2_n_sn=const_kmax=1._corrHM=True_coadd=area_fit=auto+cross_fc=1_pz-method=nz_demp_cosmo=const
    use_mpi: 1
    rerun: 0
    walkersRatio: 8
    burninIterations: 3000
    sampleIterations: 3000
